services:
  - type: web
    name: practical-portal-backend
    env: node
    plan: free
    buildCommand: npm ci --only=production
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://practicalportal.vercel.app
      - key: CORS_ORIGIN
        value: https://practicalportal.vercel.app
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        value: 3306
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: FIREBASE_ADMIN_PRIVATE_KEY
        sync: false
      - key: FIREBASE_ADMIN_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: DB_RETRY_ATTEMPTS
        value: 3
      - key: DB_RETRY_DELAY
        value: 2000
      - key: DEBUG_DB_TIMEOUT
        value: false
